backend:
  branch: master
  name: github
  repo: markus1978/temporality-homepage
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

# publish_mode: editorial_workflow
collections:
  - label: Meeting
    name: meeting
    folder: src/meetings
    create: true
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Date
        name: date
        widget: datetime
        required: true
      - label: Location
        name: location
        widget: string
        required: true
      - label: Abstract
        name: abstract
        widget: markdown
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Preview image
        name: preview
        widget: image
        required: false
      - label: Gallery
        name: gallery
        widget: list
        required: false
        field:
          label: Image
          name: image
          widget: image
  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: src/index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Members
        name: members
        file: src/pages/members.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Next meeting
        name: next-meeting
        file: src/pages/next-meeting.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Publications
        name: publications
        file: src/pages/publications.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
